# Site
title: 'Colabcademy'
description: 'Tutorials for Google Colab, Jupyter notebooks, Python, Pandas, PyTorch, TensorFlow, PAX, Sci-kit Learn, sklearn, Hugging Face, huggingface.co'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
disqus: 'demowebsite'
email: 'colabcademy@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    eddy:
      name:           Eddy Jin
      avatar:         assets/images/eddy.jpeg
      bio:            "Hi, I am Eddy, the creator of Colabcademy. I hope you like it!"
      twitter:        eddyjin_
      linkedin:       eddy-jin

    tensorflow:
      name:           TensorFlow
      avatar:         https://yt3.googleusercontent.com/ytc/AIdro_lHK_bZjMJ3JaII-PKFPZ8XKaoedexEr8EdeApMQQ=s176-c-k-c0x00ffffff-no-rj
      site:           https://www.tensorflow.org
      youtube:        TensorFlow
      github:         tensorflow

    andrejkarpathy:
      name:           Andrej Karpathy
      avatar:         https://yt3.googleusercontent.com/ytc/AIdro_n8r_ah4fmhoKuTXWp1Pgtt_8i7tarvZlJ7NSfubjo=s176-c-k-c0x00ffffff-no-rj
      site:           https://karpathy.ai
      youtube:        AndrejKarpathy
      twitter:        karpathy
      github:         karpathy

    huggingface:
      name:           HuggingFace
      avatar:         https://yt3.googleusercontent.com/ytc/AIdro_kjJCv7kKRsG_Xydp2FH767yOvpbMsqgNHiIjVR=s176-c-k-c0x00ffffff-no-rj
      site:           https://huggingface.co
      youtube:        HuggingFace
      github:         huggingface
      twitter:        huggingface

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: eddy
      avatar: /assets/images/eddy.jpeg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
