# Site
title: 'Colabcademy'
description: 'Tutorials for Google Colab, Jupyter notebooks, Python, Pandas, PyTorch, TensorFlow, PAX, Sci-kit Learn, sklearn, Hugging Face, huggingface.co'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
disqus: 'demowebsite'
email: 'colabcademy@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    eddy:
      name:           Eddy Jin
      site:           https://www.linkedin.com/in/eddy-jin
      avatar:         assets/images/eddy.jpeg
      bio:            "Hi, I am Eddy, the creator of Colabcademy. I hope you like it!"
      email:          eddy-jin@gmail.com
      twitter:        https://x.com/eddyisfunn

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: eddy
      avatar: /assets/images/eddy.jpeg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
