source "https://rubygems.org"

# gem "jekyll", "~> 4.3.3"
gem "github-pages", "~> 231", group: :jekyll_plugins

group :jekyll_plugins do
  # gem "github-pages"
  gem "jekyll-feed"
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate'
  gem 'jekyll-seo-tag'
end

gem "webrick", "~> 1.8"
